<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_55d3b7dfca5c5',
		'title' => 'Social Media',
		'fields' => array (
			array (
				'key' => 'field_55fb128508817',
				'label' => 'Networks',
				'name' => 'social_networks',
				'type' => 'repeater',
				'instructions' => 'Names should match those used in the icon layouts below.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
				'sub_fields' => array (
					array (
						'key' => 'field_55fb12a708818',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55fb12ba08819',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55fb12bf0881a',
						'label' => 'Action',
						'name' => 'action',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'field_55db4fc586311',
				'label' => 'Layouts',
				'name' => 'social_layouts',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 1,
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Add Layout',
				'sub_fields' => array (
					array (
						'key' => 'field_55377e886313',
						'label' => 'Layout Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => 'Used in the theme and widgets to identify this layout.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55db4fd286312',
						'label' => 'Icons',
						'name' => 'icons',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail-uncropped',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array (
						'key' => 'field_55db50e56a745',
						'label' => 'Styles',
						'name' => 'styles',
						'type' => 'checkbox',
						'instructions' => 'Ordered from top to bottom.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'normal' => 'Normal',
							'focus' => 'Focus',
							'hover' => 'Hover',
							'active' => 'Active',
						),
						'default_value' => array (
						),
						'layout' => 'vertical',
						'toggle' => 0,
					),
					array (
						'key' => 'field_55db4fe886313',
						'label' => 'Icon Width',
						'name' => 'width',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'px',
						'min' => 0,
						'max' => '',
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55db500286314',
						'label' => 'Icon Height',
						'name' => 'height',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'px',
						'min' => 0,
						'max' => '',
						'step' => 1,
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55db55ca6540c',
						'label' => 'Margin',
						'name' => 'margin',
						'type' => 'text',
						'instructions' => 'Margin added to each icon. Not related to the image.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '0px 0px 0px 0px',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55db501186315',
						'label' => 'Services',
						'name' => 'services',
						'type' => 'repeater',
						'instructions' => 'Left to right order of services, from the "Social Networks" tab of "Branding".',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'min' => 1,
						'max' => '',
						'layout' => 'row',
						'button_label' => 'Add Service',
						'sub_fields' => array (
							array (
								'key' => 'field_55db502c86316',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'readonly' => 0,
								'disabled' => 0,
							),
						),
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-options-social',
				),
			),
		),
		'menu_order' => 50,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;