<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
'key' => 'group_569023520f16d',
'title' => 'Articles',
'fields' => array (
array (
'key' => 'field_56902588ff216',
'label' => 'About',
'name' => '',
'type' => 'message',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'message' => '<ul class="ul-disc"><li>This automation places ad shortcodes into blog posts.</li>
	<li>It will not run on the home page, archive pages or custom templates; only single blog posts.</li>
	<li>Ads are inserted into post content and will not disrupt paragraphs.</li>
	<li>You can include the original shortcode within your post, such as <code>[ad location="Ad Location Here"]</code>. If found, that automation will be skipped.</li></ul>',
'new_lines' => 'wpautop',
'esc_html' => 0,
),
array (
'key' => 'field_56902573ff213',
'label' => 'Beginning of Post',
'name' => 'automation_post_beginning',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'collapsed' => '',
'min' => 1,
'max' => 1,
'layout' => 'row',
'button_label' => 'Add Row',
'sub_fields' => array (
array (
'key' => 'field_56902573ff214',
'label' => 'Location',
'name' => 'location',
'type' => 'select',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'choices' => array (
'' => '&ndash; Select &ndash;',
),
'default_value' => array (
),
'allow_null' => 0,
'multiple' => 0,
'ui' => 0,
'ajax' => 0,
'placeholder' => '',
'disabled' => 0,
'readonly' => 0,
),
array (
'key' => 'field_56902573ff215',
'label' => 'Required Words',
'name' => 'word_count',
'type' => 'number',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => 'Require',
'append' => 'words',
'min' => '',
'max' => '',
'step' => '',
'readonly' => 0,
'disabled' => 0,
),
),
),
array (
'key' => 'field_56902402ff20d',
'label' => 'Middle of Post',
'name' => 'automation_post_middle',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'collapsed' => '',
'min' => 1,
'max' => 1,
'layout' => 'row',
'button_label' => 'Add Row',
'sub_fields' => array (
array (
'key' => 'field_56902431ff20e',
'label' => 'Location',
'name' => 'location',
'type' => 'select',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'choices' => array (
'' => '&ndash; Select &ndash;',
),
'default_value' => array (
),
'allow_null' => 0,
'multiple' => 0,
'ui' => 0,
'ajax' => 0,
'placeholder' => '',
'disabled' => 0,
'readonly' => 0,
),
array (
'key' => 'field_569024dbff20f',
'label' => 'Required Words',
'name' => 'word_count',
'type' => 'number',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => 'Require',
'append' => 'words',
'min' => '',
'max' => '',
'step' => '',
'readonly' => 0,
'disabled' => 0,
),
),
),
array (
'key' => 'field_56902538ff210',
'label' => 'After Post',
'name' => 'automation_post_after',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'collapsed' => '',
'min' => 1,
'max' => 1,
'layout' => 'row',
'button_label' => 'Add Row',
'sub_fields' => array (
array (
'key' => 'field_56902538ff211',
'label' => 'Location',
'name' => 'location',
'type' => 'select',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'choices' => array (
'' => '&ndash; Select &ndash;',
),
'default_value' => array (
),
'allow_null' => 0,
'multiple' => 0,
'ui' => 0,
'ajax' => 0,
'placeholder' => '',
'disabled' => 0,
'readonly' => 0,
),
array (
'key' => 'field_56902538ff212',
'label' => 'Required Words',
'name' => 'word_count',
'type' => 'number',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array (
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => 'Require',
'append' => 'words',
'min' => '',
'max' => '',
'step' => '',
'readonly' => 0,
'disabled' => 0,
),
),
),
),
'location' => array (
array (
array (
'param' => 'options_page',
'operator' => '==',
'value' => 'ld-ad-settings',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'left',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

endif;