<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}
	
	acf_add_local_field_group( array(
		'key' => 'group_651c9cbb14381',
		'title' => 'RS Downloads - General Settings',
		'fields' => array(
			array(
				'key' => 'field_651c9cbb90bec',
				'label' => 'Display',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<p style="margin-top: 0;">Display a list of downloads using the "Download List" block or the shortcode <code class="code">[rs_downloads]</code>.</p>',
				'new_lines' => '',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_653c1ee2c0794',
				'label' => 'Download Page',
				'name' => 'download_page',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => 'Users will be redirected to this page if they do not have access to download a file.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'id',
				'multiple' => 0,
				'allow_null' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'rs-downloads-settings',
				),
			),
		),
		'menu_order' => 200,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_6538a8dc0c1b1',
		'title' => 'RS Downloads - Gravity Forms',
		'fields' => array(
			array(
				'key' => 'field_6538a9396bd3e',
				'label' => 'Enable Gravity Forms',
				'name' => 'enable_gravity_forms',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'Require a form submission before a download will start.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_653c4b0618750',
				'label' => 'Form Intro Message',
				'name' => 'form_intro_message',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => 'This message is displayed above the form. The form appears in a popup when someone clicks a download button, but hasn\'t submitted the form yet.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6552fe4b938a9',
				'label' => 'Confirmation Message',
				'name' => 'confirmation_message',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => 'Displayed after submitting the form, above the top of the download list.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6552b6986ac70',
				'label' => 'Gravity Form',
				'name' => 'form_id',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6538a9396bd3e',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'Please fill out the following fields [#1]',
					4 => 'Newsletter: Leaving Site Popup [#4]',
					5 => 'Newsletter: Sidebar [#5]',
					6 => 'Newsletter: Newsletter Page [#6]',
					8 => 'Lead Generation 1 [#8]',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6538b2718b5cf',
				'label' => 'Entry Expiration',
				'name' => 'entry_expiration',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => 'After submitting the form, the entry can be remembered for repeat downloads. This means the visitor only needs to fill out the form once when downloading multiple files. A duplicate entry will be created for each download.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6538a9396bd3e',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_6538b0f9256b8',
						'label' => 'Enable Expiration',
						'name' => 'enabled',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
					),
					array(
						'key' => 'field_6538b221256bb',
						'label' => 'Duration (Minutes)',
						'name' => 'minutes',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6538a9396bd3e',
									'operator' => '==',
									'value' => '1',
								),
								array(
									'field' => 'field_6538b0f9256b8',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'default_value' => 60,
						'min' => '',
						'max' => '',
						'placeholder' => 60,
						'step' => 1,
						'prepend' => '',
						'append' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'rs-downloads-settings',
				),
			),
		),
		'menu_order' => 210,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_6538e3a1525fb',
		'title' => 'Download Settings',
		'fields' => array(
			array(
				'key' => 'field_6552f6a6e447c',
				'label' => 'Statistics',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Download statistics will be listed here.',
				'new_lines' => '',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_6538e3a182426',
				'label' => 'Type',
				'name' => 'type',
				'aria-label' => '',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'file' => 'File Upload',
					'url' => 'Custom Link',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'layout' => 'horizontal',
			),
			array(
				'key' => 'field_6538e3f082427',
				'label' => 'File',
				'name' => 'file',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6538e3a182426',
							'operator' => '==',
							'value' => 'file',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6538e87619c97',
				'label' => 'Force Download',
				'name' => 'force_download',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6538e3a182426',
							'operator' => '==',
							'value' => 'file',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Force the file to download instead of previewing in the browser',
				'default_value' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_6538e3fe82428',
				'label' => 'URL',
				'name' => 'url',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6538e3a182426',
							'operator' => '==',
							'value' => 'url',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6538e4e8478ea',
				'label' => 'Button Text',
				'name' => 'button_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => 'Download',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'rs_download',
				),
			),
		),
		'menu_order' => 300,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

